---
language: go
env:
  global:
    - GO111MODULE=on
    - TEST_ASSET_KUBECTL=~/kubebuilder_1.0.8_linux_amd64/bin/kubectl
    - TEST_ASSET_KUBE_APISERVER=~/kubebuilder_1.0.8_linux_amd64/bin/kube-apiserver
    - TEST_ASSET_ETCD=~/kubebuilder_1.0.8_linux_amd64/bin/etcd

go:
  - "1.12.x"

script:
  - pwd
  - wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v1.0.8/kubebuilder_1.0.8_linux_amd64.tar.gz
  - tar xvzf kubebuilder_1.0.8_linux_amd64.tar.gz
  - make test

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
